### ISSUE TITLE
cant seem to change the transition

### ISSUE THREAD

**Issue by aarkanov** [agapoff/Lumper#2]
Hi There,

I'm trying to use your script and everything seems to be working quite well. Thank you for that :). However I cannot seem to get the transition piece to work, everytime i try to change the transition i get a

"Changing status to Done"
"Failed doing transistion at migrate.pl line 145, <> line 1."

Is there anything that i'm missing?

Your help will be greatly appreciated. 

Thank you,

Alex
@agapoff

**Comment by axtox** [comment]
Please check out PR #6 
You can take fork version of this script to be able to use it now, or wait until PR is closed

This version includes all the checks before the migration, so you will be able to locate the problem in the beginning
